language: node_js
node_js:
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
branches:
  only:
    - master
after_script:
- grunt build
env:
  global:
    - secure: "y57RTsxiIACxQ0Luc4mZT1XlnoUyNPfKsBmacHLw9a7KpmqBUCK3f+VTiLyl2ZdJnV5lTFrMtM1JTwwTprVIlAGrdHI2vuDd76DUTZoJRE6yHHl/IX1XVVo0NO4lrPkzq2DClgk0Q4I3hraLGzmp+ArD+4s2wQfFd2+ajGr+jOY="